apiVersion: v1
kind: Pod
metadata:
  name: monitoring-pod
  labels:
    app: prometheus
spec:
  containers:
  - name: prometheus
    image: prom/prometheus
    ports:
    - containerPort: 9090
    args:
    - "--config.file=/etc/prometheus/prometheus.yml"
    volumeMounts:
    - mountPath: /etc/prometheus/
      name: config-volume
  volumes:
  - name: config-volume
    configMap:
      name: prometheus-config
