apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  labels:
    app: nginx-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080  # NGINX listens on this port
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf  # Mount the config file
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
spec:
  type: NodePort  # Expose the service on a high port
  selector:
    app: nginx-reverse-proxy
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # Change to an available NodePort (this can be customized)
