apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'traffic-collector'
        static_configs:
          - targets: ['POD_NAME:9090']

      - job_name: 'backup'
        static_configs:
          - targets: ['POD_NAME:9090']
