apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'traffic-collector'
        static_configs:
          - targets: ['traffic-collector:9090']

      - job_name: 'traffic-backup'
        static_configs:
          - targets: ['traffic-backup:9090']
